import {
  type HttpMethod,
  type ParamLocation,
  type ParamBoundaryCase,
  type ApiParamConfig,
  type CoreBeApiEndpoint as ApiEndpoint,
  type ExecutionMode,
  type ApiTestCaseInput,
  type ApiTestCaseResult,
  type CoreBeRunRequest as ApiRunRequest,
  type CoreBeRunResponse as ApiRunResponse,
} from './corebe.schema'

// Re-export types for generic API tests usage.
export type {
  HttpMethod,
  ParamLocation,
  ParamBoundaryCase,
  ApiParamConfig,
  ApiEndpoint,
  ExecutionMode,
  ApiTestCaseInput,
  ApiTestCaseResult,
  ApiRunRequest,
  ApiRunResponse,
}

/**
 * Notification service endpoints.
 *
 * This array is meant to be maintained by the
 * scripts/generate-notif-endpoints.js script.
 */
export const NOTIF_ENDPOINTS: ApiEndpoint[] = [
  {
    id: 'health_get_health',
    category: 'Health',
    name: 'GET /health',
    method: 'GET',
    path: '/health',
    description: '',
    tags: [],
    params: [],
  },
  {
    id: 'notify_post_activate_user_user_id_cdate',
    category: 'Notify',
    name: 'POST /activate/user/{user_id}/{cdate}',
    method: 'POST',
    path: '/activate/user/{user_id}/{cdate}',
    description: '',
    tags: [],
    params: [],
  },
  {
    id: 'notify_post_fast_user',
    category: 'Notify',
    name: 'POST /fast-user',
    method: 'POST',
    path: '/fast-user',
    description: 'add fast user',
    tags: [],
    params: [
      {
        name: 'user_id',
        location: 'body',
        type: 'string',
        required: true,
        description: '',
        defaultValue: undefined,
        boundaryCases: [
          {
            id: 'user_id.empty',
            label: '空字符串',
            kind: 'empty',
            value: '',
            description: '空字符串',
            enabled: true,
          },
          {
            id: 'user_id.long',
            label: '超长字符串',
            kind: 'max',
            value:
              'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
            description: '超长字符串（256）',
            enabled: true,
          },
          {
            id: 'user_id.special',
            label: '特殊字符',
            kind: 'special',
            value: '特殊字符!@#',
            description: '包含特殊字符',
            enabled: true,
          },
        ],
      },
      {
        name: 'options',
        location: 'body',
        type: 'json',
        required: false,
        description: '',
        defaultValue: undefined,
        boundaryCases: [],
      },
    ],
  },
  {
    id: 'notify_delete_fast_user_user_id',
    category: 'Notify',
    name: 'DELETE /fast-user/{user_id}',
    method: 'DELETE',
    path: '/fast-user/{user_id}',
    description: '',
    tags: [],
    params: [],
  },
  {
    id: 'notify_post_fast_user_cache_user_id',
    category: 'Notify',
    name: 'POST /fast-user/cache/{user_id}',
    method: 'POST',
    path: '/fast-user/cache/{user_id}',
    description: '',
    tags: [],
    params: [],
  },
  {
    id: 'notify_post_pull',
    category: 'Notify',
    name: 'POST /pull',
    method: 'POST',
    path: '/pull',
    description: '',
    tags: [],
    params: [
      {
        name: 'userId',
        location: 'body',
        type: 'string',
        required: true,
        description: '',
        defaultValue: undefined,
        boundaryCases: [
          {
            id: 'userId.empty',
            label: '空字符串',
            kind: 'empty',
            value: '',
            description: '空字符串',
            enabled: true,
          },
          {
            id: 'userId.long',
            label: '超长字符串',
            kind: 'max',
            value:
              'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
            description: '超长字符串（256）',
            enabled: true,
          },
          {
            id: 'userId.special',
            label: '特殊字符',
            kind: 'special',
            value: '特殊字符!@#',
            description: '包含特殊字符',
            enabled: true,
          },
        ],
      },
      {
        name: 'objId',
        location: 'body',
        type: 'number',
        required: false,
        description: '',
        defaultValue: undefined,
        boundaryCases: [
          {
            id: 'objId.zero',
            label: '0',
            kind: 'zero',
            value: 0,
            description: '0 值',
            enabled: true,
          },
          {
            id: 'objId.negative',
            label: '负数',
            kind: 'negative',
            value: -1,
            description: '负数',
            enabled: true,
          },
          {
            id: 'objId.large',
            label: '大数',
            kind: 'large',
            value: 1000000,
            description: '较大数值',
            enabled: true,
          },
        ],
      },
      {
        name: 'action',
        location: 'body',
        type: 'string',
        required: true,
        description: '',
        defaultValue: undefined,
        boundaryCases: [
          {
            id: 'action.empty',
            label: '空字符串',
            kind: 'empty',
            value: '',
            description: '空字符串',
            enabled: true,
          },
          {
            id: 'action.long',
            label: '超长字符串',
            kind: 'max',
            value:
              'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
            description: '超长字符串（256）',
            enabled: true,
          },
          {
            id: 'action.special',
            label: '特殊字符',
            kind: 'special',
            value: '特殊字符!@#',
            description: '包含特殊字符',
            enabled: true,
          },
        ],
      },
      {
        name: 'max',
        location: 'body',
        type: 'number',
        required: false,
        description: '',
        defaultValue: 20,
        boundaryCases: [
          {
            id: 'max.zero',
            label: '0',
            kind: 'zero',
            value: 0,
            description: '0 值',
            enabled: true,
          },
          {
            id: 'max.negative',
            label: '负数',
            kind: 'negative',
            value: -1,
            description: '负数',
            enabled: true,
          },
          {
            id: 'max.large',
            label: '大数',
            kind: 'large',
            value: 1000000,
            description: '较大数值',
            enabled: true,
          },
        ],
      },
      {
        name: 'ifRefresh',
        location: 'body',
        type: 'boolean',
        required: false,
        description: '',
        defaultValue: undefined,
        boundaryCases: [
          {
            id: 'ifRefresh.true',
            label: 'true',
            kind: 'true',
            value: true,
            description: '布尔 true',
            enabled: true,
          },
          {
            id: 'ifRefresh.false',
            label: 'false',
            kind: 'false',
            value: false,
            description: '布尔 false',
            enabled: true,
          },
        ],
      },
      {
        name: 'tagUp',
        location: 'body',
        type: 'string',
        required: false,
        description: '',
        defaultValue: undefined,
        boundaryCases: [
          {
            id: 'tagUp.empty',
            label: '空字符串',
            kind: 'empty',
            value: '',
            description: '空字符串',
            enabled: true,
          },
          {
            id: 'tagUp.long',
            label: '超长字符串',
            kind: 'max',
            value:
              'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
            description: '超长字符串（256）',
            enabled: true,
          },
          {
            id: 'tagUp.special',
            label: '特殊字符',
            kind: 'special',
            value: '特殊字符!@#',
            description: '包含特殊字符',
            enabled: true,
          },
        ],
      },
      {
        name: 'tagDown',
        location: 'body',
        type: 'string',
        required: false,
        description: '',
        defaultValue: undefined,
        boundaryCases: [
          {
            id: 'tagDown.empty',
            label: '空字符串',
            kind: 'empty',
            value: '',
            description: '空字符串',
            enabled: true,
          },
          {
            id: 'tagDown.long',
            label: '超长字符串',
            kind: 'max',
            value:
              'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
            description: '超长字符串（256）',
            enabled: true,
          },
          {
            id: 'tagDown.special',
            label: '特殊字符',
            kind: 'special',
            value: '特殊字符!@#',
            description: '包含特殊字符',
            enabled: true,
          },
        ],
      },
      {
        name: 'tagUpTS',
        location: 'body',
        type: 'number',
        required: false,
        description: '',
        defaultValue: undefined,
        boundaryCases: [
          {
            id: 'tagUpTS.zero',
            label: '0',
            kind: 'zero',
            value: 0,
            description: '0 值',
            enabled: true,
          },
          {
            id: 'tagUpTS.negative',
            label: '负数',
            kind: 'negative',
            value: -1,
            description: '负数',
            enabled: true,
          },
          {
            id: 'tagUpTS.large',
            label: '大数',
            kind: 'large',
            value: 1000000,
            description: '较大数值',
            enabled: true,
          },
        ],
      },
      {
        name: 'tagDownTS',
        location: 'body',
        type: 'number',
        required: false,
        description: '',
        defaultValue: undefined,
        boundaryCases: [
          {
            id: 'tagDownTS.zero',
            label: '0',
            kind: 'zero',
            value: 0,
            description: '0 值',
            enabled: true,
          },
          {
            id: 'tagDownTS.negative',
            label: '负数',
            kind: 'negative',
            value: -1,
            description: '负数',
            enabled: true,
          },
          {
            id: 'tagDownTS.large',
            label: '大数',
            kind: 'large',
            value: 1000000,
            description: '较大数值',
            enabled: true,
          },
        ],
      },
      {
        name: 'level',
        location: 'body',
        type: 'string',
        required: false,
        description: '',
        defaultValue: undefined,
        boundaryCases: [
          {
            id: 'level.empty',
            label: '空字符串',
            kind: 'empty',
            value: '',
            description: '空字符串',
            enabled: true,
          },
          {
            id: 'level.long',
            label: '超长字符串',
            kind: 'max',
            value:
              'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
            description: '超长字符串（256）',
            enabled: true,
          },
          {
            id: 'level.special',
            label: '特殊字符',
            kind: 'special',
            value: '特殊字符!@#',
            description: '包含特殊字符',
            enabled: true,
          },
        ],
      },
    ],
  },
  {
    id: 'notify_post_push',
    category: 'Notify',
    name: 'POST /push',
    method: 'POST',
    path: '/push',
    description: '',
    tags: [],
    params: [
      {
        name: 'action',
        location: 'body',
        type: 'string',
        required: true,
        description: '',
        defaultValue: undefined,
        boundaryCases: [
          {
            id: 'action.empty',
            label: '空字符串',
            kind: 'empty',
            value: '',
            description: '空字符串',
            enabled: true,
          },
          {
            id: 'action.long',
            label: '超长字符串',
            kind: 'max',
            value:
              'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
            description: '超长字符串（256）',
            enabled: true,
          },
          {
            id: 'action.special',
            label: '特殊字符',
            kind: 'special',
            value: '特殊字符!@#',
            description: '包含特殊字符',
            enabled: true,
          },
        ],
      },
      {
        name: 'from_user',
        location: 'body',
        type: 'string',
        required: true,
        description: '',
        defaultValue: undefined,
        boundaryCases: [
          {
            id: 'from_user.empty',
            label: '空字符串',
            kind: 'empty',
            value: '',
            description: '空字符串',
            enabled: true,
          },
          {
            id: 'from_user.long',
            label: '超长字符串',
            kind: 'max',
            value:
              'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
            description: '超长字符串（256）',
            enabled: true,
          },
          {
            id: 'from_user.special',
            label: '特殊字符',
            kind: 'special',
            value: '特殊字符!@#',
            description: '包含特殊字符',
            enabled: true,
          },
        ],
      },
      {
        name: 'to_user',
        location: 'body',
        type: 'string',
        required: true,
        description: '',
        defaultValue: undefined,
        boundaryCases: [
          {
            id: 'to_user.empty',
            label: '空字符串',
            kind: 'empty',
            value: '',
            description: '空字符串',
            enabled: true,
          },
          {
            id: 'to_user.long',
            label: '超长字符串',
            kind: 'max',
            value:
              'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
            description: '超长字符串（256）',
            enabled: true,
          },
          {
            id: 'to_user.special',
            label: '特殊字符',
            kind: 'special',
            value: '特殊字符!@#',
            description: '包含特殊字符',
            enabled: true,
          },
        ],
      },
      {
        name: 'content',
        location: 'body',
        type: 'json',
        required: false,
        description: '',
        defaultValue: undefined,
        boundaryCases: [],
      },
      {
        name: 'enabled',
        location: 'body',
        type: 'boolean',
        required: false,
        description: '',
        defaultValue: undefined,
        boundaryCases: [
          {
            id: 'enabled.true',
            label: 'true',
            kind: 'true',
            value: true,
            description: '布尔 true',
            enabled: true,
          },
          {
            id: 'enabled.false',
            label: 'false',
            kind: 'false',
            value: false,
            description: '布尔 false',
            enabled: true,
          },
        ],
      },
      {
        name: 'toggles',
        location: 'body',
        type: 'string',
        required: false,
        description: '',
        defaultValue: undefined,
        boundaryCases: [
          {
            id: 'toggles.empty',
            label: '空字符串',
            kind: 'empty',
            value: '',
            description: '空字符串',
            enabled: true,
          },
          {
            id: 'toggles.long',
            label: '超长字符串',
            kind: 'max',
            value:
              'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
            description: '超长字符串（256）',
            enabled: true,
          },
          {
            id: 'toggles.special',
            label: '特殊字符',
            kind: 'special',
            value: '特殊字符!@#',
            description: '包含特殊字符',
            enabled: true,
          },
        ],
      },
    ],
  },
  {
    id: 'public_get_public_settings',
    category: 'Public',
    name: 'GET /public/settings',
    method: 'GET',
    path: '/public/settings',
    description: '',
    tags: [],
    params: [],
  },
  {
    id: 'public_post_public_settings',
    category: 'Public',
    name: 'POST /public/settings',
    method: 'POST',
    path: '/public/settings',
    description: '',
    tags: [],
    params: [],
  },
]
